inherit_from: "configs/horizongs/HorizonGS_road_street1_orb_persistent_fine_eval_v1.yaml"

Dataset:
  name: "HorizonGS-road-street1-orb-persistent-fine-balanced-v1"
  max_pts_num: 5000

Testset:
  name: "HorizonGS-road-street1-orb-persistent-fine-balanced-v1"
  max_pts_num: 5000
