inherit_from: "configs/horizongs/HorizonGS_road_street1_orb_persistent_fine_v1_orb.yaml"

Results:
  save_dir: "/home/wmy/workspace_vla/Online-3DGS-Monocular/Logs_horizongs_persistent"
  save_gt: False
  save_exr: False
  save_mesh: False
  skip_eval: False
