inherit_from: "configs/aerocommit/aerocommit_frequency_pose_edge025_road_street1_smoke20.yaml"

Dataset:
  name: "HorizonGS-road-street1-aerocommit-frequency-pose-edge050-smoke20"

Testset:
  name: "HorizonGS-road-street1-aerocommit-frequency-pose-edge050-smoke20"

Mapper:
  post_refinement:
    pose_prepass_frequency_weight: 0.50
