inherit_from: "configs/aerocommit/aerocommit_frequency_pose_appearance20_road_street1_smoke40.yaml"

Dataset:
  name: "HorizonGS-road-street1-aerocommit-sparse-track-only-smoke20"
  end_cutoff: 138

Testset:
  name: "HorizonGS-road-street1-aerocommit-sparse-track-only-smoke20"
  end_cutoff: 138

Model:
  frequency_sampling:
    preserve_sparse_track_geometry: true
