inherit_from: "configs/aerocommit/aerocommit_precomputed_surface_detail_road_street1_smoke20.yaml"

Dataset:
  name: "HorizonGS-road-street1-aerocommit-precomputed-surface-detail-smoke40"
  end_cutoff: 118

Testset:
  name: "HorizonGS-road-street1-aerocommit-precomputed-surface-detail-smoke40"
  end_cutoff: 118
