inherit_from: "configs/aerocommit/aerocommit_frequency_responsibility_sh2_panoair_seq1_full.yaml"

Dataset:
  name: "PanoAir-seq1-rtk-triangulated-aerocommit-sh2-smoke200"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_rtk_triangulated_smoke200"
  end_cutoff: 0

Testset:
  name: "PanoAir-seq1-rtk-triangulated-aerocommit-sh2-smoke200"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_rtk_triangulated_smoke200"
  end_cutoff: 0
