inherit_from: "configs/aerocommit/aerocommit_frequency_sampling_road_street1_smoke20.yaml"

Dataset:
  name: "HorizonGS-road-street1-aerocommit-frequency-sampling-noshrink-smoke20"

Testset:
  name: "HorizonGS-road-street1-aerocommit-frequency-sampling-noshrink-smoke20"

Model:
  frequency_sampling:
    max_footprint_shrink_fraction: 0.0
