inherit_from: "configs/aerocommit/baseline_road_street1.yaml"

Dataset:
  name: "HorizonGS-road-street1-aerocommit-baseline-smoke20"
  end_cutoff: 138

Testset:
  name: "HorizonGS-road-street1-aerocommit-baseline-smoke20"
  end_cutoff: 138

Mapper:
  post_refinement:
    max_steps: 200
    opt_cam: false
