inherit_from: "/home/wmy/workspace_vla/Online-3DGS-Monocular/configs/experiments_7_22/road_balanced_matched_modp_input.yaml"

Dataset:
  name: "HorizonGS-road-street1-fast-equal-capacity"
  max_pts_num: 10000

Testset:
  name: "HorizonGS-road-street1-fast-equal-capacity"
  max_pts_num: 10000
