inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_post_rr_mse25_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-post-rr-mse50-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-post-rr-mse50-200"

Mapper:
  post_refinement:
    appearance_mse_mix: 0.50
