inherit_from: "configs/frontview_uav/panoair_orbvi_residual_utility_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-cover-200"

Testset:
  name: "PanoAir-frontview-orbvi-residual-cover-200"

FrontViewResidualCover:
  selection_mode: "utility_coverage"
