inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_color15_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r015-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r015-full"

FrontViewScaleCover:
  appearance_certificate_enabled: true
  appearance_min_residual: 0.15
  appearance_min_depth_confidence: 0.0
  appearance_allow_sparse: true
