inherit_from: "configs/frontview_uav/panoair_orbvi_rift_footprint_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-rift-footprint-l2-200"

Testset:
  name: "PanoAir-frontview-orbvi-rift-footprint-l2-200"

FrontViewIdentityLOD:
  max_lod_level: 2
