inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-vial-c16-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-vial-c16-200"

FrontViewSampling:
  anchor_selection_mode: "projective_coverage"
  anchor_cell_px: 16
