inherit_from: "configs/frontview_uav/panoair_orbvi_residual_cover_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-cover-smoke10"
  stride: 20

Testset:
  name: "PanoAir-frontview-orbvi-residual-cover-smoke10"
  stride: 20

Results:
  skip_eval: true
