inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_rcas_r015_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-r015-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-r015-shuffled-200"

FrontViewScaleCover:
  shuffle_appearance_certificates: true
