inherit_from: "configs/frontview_uav/panoair_tgbr_compute_dense_full.yaml"

Dataset:
  name: "PanoAir-tgbr-sparse-band-full"

Testset:
  name: "PanoAir-tgbr-sparse-band-full"

StreamingAppearanceLOD:
  sparse_model_export: true
