inherit_from: "configs/frontview_uav/panoair_orbvi_residual_retire_opacity_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-retire-gradient-200"

Testset:
  name: "PanoAir-frontview-orbvi-residual-retire-gradient-200"

FrontViewResidualCover:
  retirement_score_mode: "gradient"
  retirement_expansion_weight: 0.0
