inherit_from: "configs/frontview_uav/panoair_tgbr_compute_routed_cap60_full.yaml"

Dataset:
  name: "PanoAir-tgbr-compute-routed-cap60-shuffled-full"

Testset:
  name: "PanoAir-tgbr-compute-routed-cap60-shuffled-full"

StreamingAppearanceLOD:
  selection_mode: "gradient_shuffled"
