inherit_from: "configs/frontview_uav/panoair_orbvi_eosc_r0p3_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-eosc-r0p3-full"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_orbslam3_mono_vi_fused_full_v1"
  end_cutoff: 0

Testset:
  name: "PanoAir-frontview-orbvi-eosc-r0p3-full"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_orbslam3_mono_vi_fused_full_v1"
  end_cutoff: 0
