inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_rcas_track_r008_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r008-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r008-shuffled-200"

FrontViewScaleCover:
  shuffle_appearance_certificates: true
