inherit_from: "configs/frontview_uav/panoair_tgbr_tailcert7_strict_200.yaml"

Dataset:
  name: "PanoAir-tgbr-tailcert7-skip-200"

Testset:
  name: "PanoAir-tgbr-tailcert7-skip-200"

StreamingAppearanceLOD:
  optimization_budget_tail_collapse_mode: "none"
