inherit_from: "configs/frontview_uav/panoair_tgbr_tailcert7_strict_200.yaml"

Dataset:
  name: "PanoAir-tgbr-tailcert5-gain-200"

Testset:
  name: "PanoAir-tgbr-tailcert5-gain-200"

StreamingAppearanceLOD:
  optimization_budget_min_steps: 5
