inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_pfc_floor25_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-floor25-color10-gpu-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-floor25-color10-gpu-full"

FrontViewScaleCover:
  query_backend: "pytorch3d_knn"
  color_distance_threshold: 0.10
