inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_temporal2_any_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-temporal2-dup-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-temporal2-dup-200"

FrontViewBirth:
  temporal_reject_duplicates: true
