inherit_from: "configs/frontview_uav/panoair_orbvi_residual_utility_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-utility-budget1-200"

Testset:
  name: "PanoAir-frontview-orbvi-residual-utility-budget1-200"

FrontViewResidualCover:
  budget_scale: 1.0
