inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_active_color15_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-active-color15-full"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_orbslam3_mono_vi_fused_full_v1"
  end_cutoff: 0

Testset:
  name: "PanoAir-frontview-orbvi-tsc-active-color15-full"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_PanoAir/seq1_orbslam3_mono_vi_fused_full_v1"
  end_cutoff: 0
