inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_eqr_sh2_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-eqr-sh2-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-eqr-sh2-shuffled-200"

FrontViewScaleCover:
  shuffle_evidence_quota: true
