inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_color15_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-r008-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-r008-200"

FrontViewScaleCover:
  appearance_certificate_enabled: true
  appearance_min_residual: 0.08
  appearance_min_depth_confidence: 0.0
