inherit_from: "configs/frontview_uav/panoair_orbvi_residual_retire_gradient-opacity_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-retire-late170-full"

Testset:
  name: "PanoAir-frontview-orbvi-residual-retire-late170-full"

FrontViewResidualCover:
  retirement_start_frame: 1000
  retirement_capacity_base: 390000
  retirement_capacity_per_frame: 170.0
