inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_temporal1_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-temporal2-any-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-temporal2-any-200"

FrontViewBirth:
  temporal_reference_frames: 2
