inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_color15_sh2_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-r0p3-color15-sh2-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-r0p3-color15-sh2-shuffled-200"

FrontViewScaleCover:
  shuffle_occupancy: true
