inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_fcbo64_revisit1700.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-fcbo64-shuffled-revisit1700"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-fcbo64-shuffled-revisit1700"

FrontViewScaleCover:
  shuffle_frustum_conflict_budget: true
