inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_color15_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-color15-revisit1700"
  end_cutoff: 530

Testset:
  name: "PanoAir-frontview-orbvi-tsc-color15-revisit1700"
  begin_cutoff: 1000
  end_cutoff: 530
