inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_mix50_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-post-range-rr-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-post-range-rr-200"

Mapper:
  post_refinement:
    sampling_method: "frontview_range_round_robin"
