inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_replay_cyclic_k2_s4_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-replay-cyclic-k2-s6-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-replay-cyclic-k2-s6-200"

Mapper:
  KFGraph:
    frontview_replay_strata: 6
