inherit_from: "configs/frontview_uav/panoair_orbvi_pcra_s3_r1p5_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-pcra-s2-r1p5-200"

Testset:
  name: "PanoAir-frontview-orbvi-pcra-s2-r1p5-200"

FrontViewResidualCover:
  covariance_overlap_sigma: 2.0
