inherit_from: "configs/frontview_uav/panoair_orbvi_pbsd_uav_4000_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-pbsd-uav-4800-200"

Testset:
  name: "PanoAir-frontview-orbvi-pbsd-uav-4800-200"

Model:
  extra_pts_num: 4800
