inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_replay_uniform_k3_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-replay-uniform-k3-s8-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-replay-uniform-k3-s8-200"

Mapper:
  optimization_iters: 8
