inherit_from: "configs/frontview_uav/panoair_orbvi_residual_cover_wide_budget1_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-residual-cover-wide-budget1-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-residual-cover-wide-budget1-shuffled-200"

FrontViewResidualCover:
  shuffle_evidence: true
