inherit_from: "configs/frontview_uav/panoair_tgbr_tailcert5_gain125_200.yaml"

Dataset:
  name: "PanoAir-tgbr-tailcert5-gain125-tail02-200"

Testset:
  name: "PanoAir-tgbr-tailcert5-gain125-tail02-200"

StreamingAppearanceLOD:
  optimization_budget_max_relative_tail: 0.02
