inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-r0p3-ratio2-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-r0p3-ratio2-200"

FrontViewScaleCover:
  scale_compatibility: 2.0
