inherit_from: "configs/frontview_uav/panoair_orbvi_pbsd_far_projective80_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-pbsd-far-projective80-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-pbsd-far-projective80-shuffled-200"

FrontViewFarField:
  shuffle_responsibility: true
  shuffle_seed: 42
