inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_pfc_dcsc45_revisit1700_gpu.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-dcsc45-shuffled-revisit1700-gpu"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-dcsc45-shuffled-revisit1700-gpu"

FrontViewScaleCover:
  shuffle_directional_ownership: true
