inherit_from: "configs/frontview_uav/panoair_tgbr_directional_step_percentile_full.yaml"

Dataset:
  name: "PanoAir-tgbr-directional-step-shuffled-full"

Testset:
  name: "PanoAir-tgbr-directional-step-shuffled-full"

StreamingAppearanceLOD:
  directional_step_budget_selection_mode: "shuffled"
  directional_step_budget_shuffle_very_low_fraction: 0.30
  directional_step_budget_shuffle_low_fraction: 0.40
