inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r1_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-smoke10"
  stride: 20

Testset:
  name: "PanoAir-frontview-orbvi-tsc-smoke10"
  stride: 20

Results:
  skip_eval: true
