inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_rcas_track_r015_shuffled_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r008-shuffled-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-rcas-track-r008-shuffled-full"

FrontViewScaleCover:
  appearance_min_residual: 0.08
