inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_pfc_floor25_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-floor25-color20-200"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-floor25-color20-200"

FrontViewScaleCover:
  color_distance_threshold: 0.20
