inherit_from: "configs/frontview_uav/panoair_tgbr_directional_views_b_200.yaml"

Dataset:
  name: "PanoAir-tgbr-directional-views-f-200"

Testset:
  name: "PanoAir-tgbr-directional-views-f-200"

StreamingAppearanceLOD:
  directional_view_budget_very_low_compact_steps: 7
  directional_view_budget_low_compact_steps: 4
