inherit_from: "configs/frontview_uav/panoair_tgbr_directional_views_a_full.yaml"

Dataset:
  name: "PanoAir-tgbr-directional-views-shuffled-full"

Testset:
  name: "PanoAir-tgbr-directional-views-shuffled-full"

StreamingAppearanceLOD:
  directional_view_budget_selection_mode: "shuffled"
  directional_view_budget_shuffle_very_low_fraction: 0.30
  directional_view_budget_shuffle_low_fraction: 0.40
