inherit_from: "configs/frontview_uav/panoair_tgbr_directional_views_percentile_200.yaml"

Dataset:
  name: "PanoAir-tgbr-directional-views-percentile-balanced-200"

Testset:
  name: "PanoAir-tgbr-directional-views-percentile-balanced-200"

StreamingAppearanceLOD:
  directional_view_budget_very_low_compact_steps: 7
  directional_view_budget_low_compact_steps: 5
  directional_view_budget_sampling_mode: "cyclic_balanced"
