inherit_from: "configs/frontview_uav/panoair_tgbr_tailcert5_gain125_tail02_200.yaml"

Dataset:
  name: "PanoAir-tgbr-tailcert5-gain150-tail02-200"

Testset:
  name: "PanoAir-tgbr-tailcert5-gain150-tail02-200"

StreamingAppearanceLOD:
  optimization_budget_tail_gain_factor: 1.50
