inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_pfc_floor25_gpu_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-isdo-gpu-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-isdo-gpu-full"

FrontViewScaleCover:
  sparse_track_identity_enabled: true
