inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_pfc_floor25_gpu_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-dcsc45-gpu-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-pfc-dcsc45-gpu-full"

FrontViewScaleCover:
  directional_ownership_enabled: true
  directional_max_angle_deg: 45.0
