inherit_from: "configs/frontview_uav/panoair_orbvi_pcra_s3_r1p5_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-pcra-s3-r1p5-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-pcra-s3-r1p5-shuffled-200"

FrontViewResidualCover:
  shuffle_covariance_competition: true
