inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_tgbr75_sh3_full.yaml"

Dataset:
  name: "PanoAir-tgbr-spectral-baseline-full"

Testset:
  name: "PanoAir-tgbr-spectral-baseline-full"

CudaMemoryProfile:
  enabled: true

Results:
  skip_eval: true
