inherit_from: "configs/frontview_uav/panoair_orbvi_tsc_r0p3_full.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tsc-r0p266-full"

Testset:
  name: "PanoAir-frontview-orbvi-tsc-r0p266-full"

FrontViewScaleCover:
  radius_multiplier: 0.266
