inherit_from: "configs/frontview_uav/panoair_orbvi_tlpb_adaptive_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-tlpb-mix25-200"

Testset:
  name: "PanoAir-frontview-orbvi-tlpb-mix25-200"

FrontViewBirth:
  priority_fraction: 0.25
