inherit_from: "configs/frontview_uav/panoair_orbvi_rift_footprint_dense_l2_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-rift-footprint-dense-l2-shuffled-200"

Testset:
  name: "PanoAir-frontview-orbvi-rift-footprint-dense-l2-shuffled-200"

FrontViewIdentityLOD:
  shuffle_identity: true
  shuffle_seed: 42
