inherit_from: "configs/frontview_uav/panoair_tgbr_directional_budget_a_200.yaml"

Dataset:
  name: "PanoAir-tgbr-directional-budget-c-200"

Testset:
  name: "PanoAir-tgbr-directional-budget-c-200"

StreamingAppearanceLOD:
  directional_step_budget_very_low_degrees: 1.00
  directional_step_budget_low_degrees: 2.00
