inherit_from: "configs/frontview_uav/panoair_orbvi_rift_handoff_floor25_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-rift-handoff-floor25-smoke10"
  stride: 20

Testset:
  name: "PanoAir-frontview-orbvi-rift-handoff-floor25-smoke10"
  stride: 20

Results:
  skip_eval: true
