inherit_from: "configs/frontview_uav/panoair_orbvi_cgtfl_w10_200.yaml"

Dataset:
  name: "PanoAir-frontview-orbvi-cgtfl-w20-200"

Testset:
  name: "PanoAir-frontview-orbvi-cgtfl-w20-200"

FrontViewIdentityLOD:
  world_gate_scale: 2.0
