inherit_from: "configs/progressive_uav/progressive_uav_road_street1_quality_smoke20_long.yaml"

Dataset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20-sh1"

Testset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20-sh1"

Model:
  sh_degree: 1
