inherit_from: "configs/progressive_uav/progressive_uav_road_street1_baseline_quality.yaml"

Dataset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20"
  end_cutoff: 138

Testset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20"
  end_cutoff: 138

Mapper:
  post_refinement:
    max_steps: 200
    opt_cam: false
