inherit_from: "configs/progressive_uav/progressive_uav_road_street1_observability_fast.yaml"

Dataset:
  name: "HorizonGS-road-street1-observability-fast-short"
  end_cutoff: 118

Testset:
  name: "HorizonGS-road-street1-observability-fast-short"
  end_cutoff: 118
