inherit_from: "configs/progressive_uav/progressive_uav_road_street1_baseline_quality.yaml"

Dataset:
  name: "HorizonGS-road-street1-progressive-quality-short"
  end_cutoff: 118

Testset:
  name: "HorizonGS-road-street1-progressive-quality-short"
  end_cutoff: 118
