inherit_from: "configs/progressive_uav/progressive_uav_road_street1_baseline_quality_smoke20.yaml"

Dataset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20-long"

Testset:
  name: "HorizonGS-road-street1-progressive-quality-smoke20-long"

Mapper:
  post_refinement:
    max_steps: 1000
    opt_cam: false
