inherit_from: "configs/airvln/AerialVLNS_scene10_10x_orb.yaml"

Dataset:
  name: "AerialVLNS-scene10-10x-frame173"
  begin_cutoff: 173
  end_cutoff: 1577

Testset:
  name: "AerialVLNS-scene10-10x-frame173"
  begin_cutoff: 173
  end_cutoff: 1577