inherit_from: "configs/local_smoke/BikeShop_orb_smoke.yaml"

Dataset:
  name: "AerialVLNS-scene10-val_seen-0"
  type: "aria"
  data_source: "orb"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_AirVLN/aerialvln_s_scene10_val_seen_0"
  num_threads: 0
  begin_cutoff: 0
  end_cutoff: 156
  max_pts_num: 2000
  vignette: False
  use_vignette_type: "post-render"
  Calibration:
    fx: 640.000000
    fy: 640.000000
    cx: 640.000000
    cy: 360.000000
    width: 1280
    height: 720
    near: 0.01
    far: 1000


Testset:
  name: "AerialVLNS-scene10-val_seen-0"
  type: "aria"
  data_source: "orb"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/Online3DGS_AirVLN/aerialvln_s_scene10_val_seen_0"
  num_threads: 0
  begin_cutoff: 0
  end_cutoff: 156
  max_pts_num: 2000
  vignette: False
  use_vignette_type: "post-render"
  Calibration:
    fx: 640.000000
    fy: 640.000000
    cx: 640.000000
    cy: 360.000000
    width: 1280
    height: 720
    near: 0.01
    far: 1000


Results:
  save_dir: "./Logs_airvln_smoke"
  save_gt: False
  save_exr: False
  save_mesh: False
  skip_eval: True

Mapper:
  use_multi_reso: False
  initialization_frames: 2
  optimization_iters: 1
  initialization_iters: 1
  post_refinement:
    max_steps: 0
    opt_cam: False
  KFGraph:
    kf_interval: 1
    global_window_size: 1
  CameraOptimizer:
    pose_refine_init_steps: 0
    pose_opt_steps: 0

Model:
  extra_pts_num: 64
  camera_scale_rescalar: 0.25
  scene_scale: 1.0
