inherit_from: /home/wmy/workspace_vla/Online-3DGS-Monocular/configs/360dvo_coverage_recovery/mountains_full.yaml

Dataset:
  name: 360DVO-CoverageRecoveryMapDepthR095S8-mountains

Testset:
  name: 360DVO-CoverageRecoveryMapDepthR095S8-mountains

FrontViewCoverageRecovery:
  depth_fallback_map_enabled: true
  depth_fallback_map_front_ratio: 0.95
  depth_fallback_scale_multiplier: 8.0
