inherit_from: "configs/mydata/village1_best_tgbr75.yaml"

Dataset:
  name: "MyData-village3-FrontViewBest-TGBR75"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/mydata/village3"

Testset:
  name: "MyData-village3-FrontViewBest-TGBR75"
  dataset_path: "/home/wmy/workspace_vla/Online-3DGS-Monocular/data/mydata/village3"
